project_id = "mgpzuralipywzhmczqhf"

[functions.create-user]
verify_jwt = false

[functions.test-api-connection]
verify_jwt = true

[functions.test-home-assistant]
verify_jwt = true

[functions.fitbit-oauth-start]
verify_jwt = true

[functions.fitbit-oauth-callback]
verify_jwt = false

[functions.sync-fitbit-data]
verify_jwt = false

[functions.google-oauth-start]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = false

[functions.alexa-oauth-start]
verify_jwt = true

[functions.alexa-oauth-callback]
verify_jwt = false

[functions.alexa-webhook]
verify_jwt = false

[functions.sync-amazon-routines]
verify_jwt = true

[functions.alexa-profile]
verify_jwt = true

[functions.sync-google-calendar]
verify_jwt = true

[functions.sync-alexa-reminders]
verify_jwt = true

[functions.list-google-calendars]
verify_jwt = true