project_id = "mgpzuralipywzhmczqhf"

[functions.create-user]
verify_jwt = false

[functions.test-api-connection]
verify_jwt = true

[functions.fitbit-oauth-start]
verify_jwt = true

[functions.fitbit-oauth-callback]
verify_jwt = false