// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgpzuralipywzhmczqhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ncHp1cmFsaXB5d3pobWN6cWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjE1NTcsImV4cCI6MjA3MzA5NzU1N30.iZXoTKwXv5uJYfEIhnI0ngTi3k2u25I-pQYJwWF_rpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});